### ISSUE TITLE
[Feature Request] Introduce Universal Uploader

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#149] opened 2024-02-10 23:25 UTC
A dedicated screen that would allow the user to point VPS to a single folder per table where all updates and/or new table files exist. VPS would then scan and add/update everything as needed. 

draft requirements...

- standardized Folder structure for all needed media:  <table root> with individual folders for all items under that, like... LaunchAudio, Audio, Help/Instructions, Info, PuP-Pack, B2S, ROM, NVRAM, AltSound, AltColor, etc
- for adding new :: VPS adds everything as you'd expect today
- for updating :: VPS asks to append or overwrite... only relevant for media; VPX & B2S would always overwrite of course.
- When PuP-Pack is in add/update, show link to pup-folder so user can 1-click to open, thus quickly configure the PuP Options as needed. (while best to config before upload but many do not understand the BAT is only copying files - so giving them a link is nice)
- option to mark table status as 'complete' and Dismiss all notifications for it

**Comment by syd711** [comment] 2024-02-12 08:47
The issue is similar to https://github.com/syd711/vpin-studio/issues/153. 
I know its not the same as described/requested there, but the solution there is the same that I have in mind like for this ticket.
Instead of providing a folder structure on the client, I prefer the server being smarter regarding uploads.

**Comment by syd711** [comment] 2024-02-16 18:46
I have updated the title to emphasize the solution for this. I hope this will be a sufficient solution for you when finished.

**Comment by syd711** [comment] 2024-05-30 16:45
Fixed with 2.20.0.

**Closed by syd711** 2024-05-30 16:45 UTC
Labels: enhancement, change-request, planned
