### ISSUE TITLE
[Bug] Drop-In Assets feature - several issues

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#424] opened 2024-09-01 16:20 UTC
1. If you add uncompressed media like JPG or MP4 will will not detect the added media. Soon as I added a ZIP file, the list shows all... ZIP, JPGs, MP4s

But, you still cannot install the JPGs or MP4s, the Install button is grey, only the ZIP has a lit Install button

<img width="445" alt="image" src="https://github.com/user-attachments/assets/b373ae7c-82c8-467d-83c5-fe49fa76bf17">

2. dragging a PNG doesnt work. I tried dragging the main grid and also directly to the Asset Manager's specific item (Help, etc)... neither work

3. Dragging the ZIP 'works' and looks like it will install, but it does not install anything or ask what to do with the media (the zip contains multiple images, etc)

**Comment by leprinco** [comment] 2024-09-01 23:35
what about adding a media upload to the global uploader ? 
Associated to png, jpg and mp4, it will ask for which screen the image would be added
Also a flag to choose replace / append mode
Uppon confirmation, the media is added to the medias of the selected game

**Comment by Ltek** [comment] 2024-09-02 18:55
> what about adding a media upload to the global uploader ? Associated to png, jpg and mp4, it will ask for which screen the image would be added Also a flag to choose replace / append mode Uppon confirmation, the media is added to the medias of the selected game

I'm unclear what you are asking... this bug report is specific to Drop-In Assets as show/describe. The prior upload methods work when -not- using Drop-In Asset menu

**Comment by leprinco** [comment] 2024-09-04 13:53
1a) is certainly a duplicate of #432, it is fixed 
Dropping a png in the folder should make it appear immediately

1b), 2) and 3) is as per design so far. There is no global installer for neither images nor videos. If you drag a png onto the tables, it is not reactive. This is same rule from drop-in, it cannot be dragged. And as a result of absence of such an installer, the install button is grey out.
![image](https://github.com/user-attachments/assets/f514d669-84b1-4790-a033-17b52ab88f6b)

=> and also this is why I suggested to add a media installer, so a popup in which user could select the media type and have it installed. But need more discussion with @syd711  on this
![image](https://github.com/user-attachments/assets/debdadc7-41ae-40da-b16f-342566822dde)

Also please note that you can drop on the table media section
![image](https://github.com/user-attachments/assets/df77daae-655d-4072-aac6-cd8a7e0fc98c)

**Comment by syd711** [comment] 2024-09-04 15:22
That sums it up. I will just hide the "install" button for these assets to avoid confusion.

**Comment by syd711** [comment] 2024-09-06 12:06
Fixed with 3.5.0

**Closed by syd711** 2024-09-06 12:06 UTC
Labels: bug, fixed
