### ISSUE TITLE
Many Pinball Tables Lacking Highscores

### ISSUE THREAD

**Issue by ecchodun** [syd711/vpin-studio#165] opened 2024-02-27 01:43 UTC
First off, love vpin-studio.  This is a great enhancement to the vpin environment and I'm greatly appreciative of the time and effort put into this project by syd711.  Now, my issue.  I've read troubleshooting high score data not displaying, but I have too many tables where this is an issue.  The following tables are not providing any high score data:

Funhouse
Ghostbusters
Gilligan's Island
Jaws
John Wick
Kiss
Medieval Madness
Nascar
Pirates of the Caribean
Rocky
Star Trek LE
Star Wars (Data East 1992)
Theatre of Magic
Twilight Zone

Now some of these I get why they might now work like Jaws or John Wick (original tables), but why wouldn't Twilight Zone work?

**Comment by syd711** [comment] 2024-02-27 06:23
Hi ecchodun! Thanks for the feedback!
I have most of these tables and now at least half of them are be working.
I only know that Star Wars (Data East) isn't, but about the rest:
Could you attach all log files here? I assume something is off with the installation.

**Comment by ecchodun** [comment] 2024-02-27 13:21
Embarrassed, but which log files are you referring to and where are they located?

**Comment by syd711** [comment] 2024-02-27 13:23
All .log files in the installation folder of the server.

**Comment by ecchodun** [comment] 2024-02-27 14:10
See attached.
[vpin-studio-server.2024-02-25.log](https://github.com/syd711/vpin-studio/files/14420797/vpin-studio-server.2024-02-25.log)
[vpin-studio-server.2024-02-26.log](https://github.com/syd711/vpin-studio/files/14420798/vpin-studio-server.2024-02-26.log)
[vpin-studio-server.log](https://github.com/syd711/vpin-studio/files/14420799/vpin-studio-server.log)
[vpin-studio-ui.2024-02-22.log](https://github.com/syd711/vpin-studio/files/14420800/vpin-studio-ui.2024-02-22.log)
[vpin-studio-ui.log](https://github.com/syd711/vpin-studio/files/14420801/vpin-studio-ui.log)

**Comment by syd711** [comment] 2024-02-27 15:27
I didn't find something in the log. But lets check some details, using Funhouse as a reference.
The table data dialog should look like this:

![image](https://github.com/syd711/vpin-studio/assets/1169826/7c93dc99-a88d-447b-a47c-0a86fe4b6af2)

After playing the table at least once, you can refresh the highscore in the highscore section and should see a result:

![image](https://github.com/syd711/vpin-studio/assets/1169826/f629db94-7c29-4a65-9dcc-0c44a89d8c10)

My emulator setup looks like this:
![image](https://github.com/syd711/vpin-studio/assets/1169826/d9b0698f-7589-4e63-9c2a-d7a5f8c994d7)

**Comment by ecchodun** [comment] 2024-02-27 17:02
Never mind.  I'm getting them to work by changing the "Rom Name" to that data located in "Scanned Rom Name".  I'm not sure why they aren't the same?

**Comment by syd711** [comment] 2024-02-27 18:16
The "Scanned Data" are the values the VPin Studio extracts out of the VPX file. They are not necessarily correct, but usually pretty good. The actual ROM name field is the value stored in the PinUP Popper database and is used by default. If not set, the scanned value will be used instead.

**Comment by syd711** [comment] 2024-03-02 16:55
I hope with the given information the issue is solved. There will never be a support for all tables, but at least the Studio should show you if a table is supported or not. The database that contains the supported tables will increase over time. 

The score settings validation has been improved with 2.14.0, so I close this issue for now.

**Closed by syd711** 2024-03-02 16:55 UTC
