### ISSUE TITLE
PupPack Video Issues

### ISSUE THREAD

**Issue by yoshi98bc** [syd711/vpin-studio#142] opened 2024-02-07 00:34 UTC
I have noticed that Pupacks during game play stutter a lot when VPin studio is running.  When I shut Vpin studio down they have no issues.  Tron Legacy is an example with installed PupPack.  Before I lauch any tables with PupPacks I have to shut down the Vpin service.  This is not ideal.

I did add an app called Pinaffinity available at mjrnet and it helps a little when I add VPin studio to the Pinball core.  But doesnt eliminate the problem.  '

Thanks

**Comment by syd711** [comment] 2024-02-07 08:12
> When I shut Vpin studio..

Just to avoid misunderstanding. When you launch PinUP Popper and start a table from, you kill to server(!) process (not the UI) first. The CPU usage of the server is usually close to zero since, especially during the game when not used otherwise.
Can you attach the server log to be sure? The only explanation would be a repetitive error which would show up in the logs.

If you have the client running, especially with the preview enabled and active, the CPU usage of the client is very high, playing a set of videos in parallel.
The issues is reported here https://github.com/syd711/vpin-studio/issues/126 and fixed with the next update.

**Comment by yoshi98bc** [comment] 2024-02-08 00:33
So when tested the video stutters when vpin studio server is running and client is not connected.  When I terminate vpin studio everything runs fine.  
[vpin-studio-server.log](https://github.com/syd711/vpin-studio/files/14202985/vpin-studio-server.log)

**Comment by syd711** [comment] 2024-02-09 20:38
I tested on two different PCs and will test again on my cab next week.
I assume the issue is not directly related to pup packs but more because the of the Windows Defender.
Had you opened the task manager and checked the CPU usages of the processes? I would try to exclude the vpin-studio-server.exe from Windows Defender and check if the problem still occurs.

**Comment by yoshi98bc** [comment] 2024-02-10 02:46
I excluded it from windows defender. Didnt change anything. Then i turned
off windows defender. Seemed to fix it. After a restart. Excluding it
should have worked. I may have done it wrong. Could you tell me easy way to
exclude it? Thanks. I would like to turn windows defender back on

**Comment by syd711** [comment] 2024-02-10 07:19
I noticed this defender stuff only on my "real" cabinet. I turned the defender off there too. But I'll recheck if I can get the exclusion stuff there working next week. (I don't have access right now).

**Comment by yoshi98bc** [comment] 2024-02-10 13:41
Thanks so much. I am also thinking about rolling back my nvidia drivers.
Ive heard about issues with latest release. Does your program interact with
those drivers in any way?

**Comment by syd711** [comment] 2024-02-10 14:08
No, I don't "look that deep" into the OS and do not depend on any drivers.

**Comment by syd711** [comment] 2024-02-13 06:09
So I was able to reproduce this on my cabinet.
Excluding the server did fix the problem.
I have documented this here:
https://github.com/syd711/vpin-studio/wiki/Troubleshooting#the-server-is-causing-high-cpu-usage-by-windows-defender

**Comment by syd711** [comment] 2024-02-16 18:51
I assume this ticket can be closed. Feel free to reopen it, if something is still causing this issue.

**Closed by syd711** 2024-02-16 18:51 UTC
Labels: bug, documentation

**Comment by yoshi98bc** [comment] 2024-02-16 19:06
It seems to be working fine now
