### ISSUE TITLE
[Bug] Can't update vps database

### ISSUE THREAD

**Issue by bipbipbip** [syd711/vpin-studio#615] opened 2024-11-21 05:04 UTC
**Describe the bug**
when i try to update the vps database an error message appear

**To Reproduce**
go to the vps tables tab
click on reload all vps data
error message appear : error in progressing: Not on FX application thread; currentThread = Thread-34

**Expected behavior**
it should update the vps database with the new tables

**Desktop (please complete the following information):**
 - OS: win 11
 - Browser chrome

**Comment by syd711** [comment] 2024-11-22 14:55
I just tried it several time but wasn't able to reproduce this.
If this is still reproduceable for you, could you attach the zipped log files from the installation folder of your client?

**Comment by bipbipbip** [comment] 2024-11-23 05:43
ok here the zip
[logs.zip](https://github.com/user-attachments/files/17878627/logs.zip)

**Comment by syd711** [comment] 2024-11-23 21:43
Thanks, these helped a lot. It seems that the issue is related because of a "Pinball M".
I assume the emulator is not detected which results in some follow up errors.
I will install Pinball M and check this.
Could you also attach a screenshot of your Pinball M emulator configuration in Popper?

**Comment by bipbipbip** [comment] 2024-11-24 05:12
thanks, my config for this emulator is from popper wiki
![Screenshot 2024-11-24 060849](https://github.com/user-attachments/assets/ae70a384-38c5-4d51-84e8-1521d70e927a)

**Comment by bipbipbip** [comment] 2024-11-29 05:22
hi,
when i looked at the logs i'm not sure the problem was pinball m but rather visual pinball 9 ( emu id 6), so i deleted games in this emulator (only 2 games) and now vps database update is working

**Comment by syd711** [comment] 2024-11-29 06:52
I have improved the game loading so that errors there shouldn't affect this update anymore. The fix comes with the next update.

**Comment by syd711** [comment] 2024-11-29 07:39
Fixed with 3.10.3

**Closed by syd711** 2024-11-29 07:39 UTC
Labels: bug, fixed
