### ISSUE TITLE
Funhouse fh_106h.nv is not producing a high score result

### ISSUE THREAD

**Issue by buffdriver** [syd711/vpin-studio#173] opened 2024-03-03 21:03 UTC
VPin-Studio is unable to produce a high score card for funhouse.  It produces the message "Failed to read high score".  This was previously working on my Pincab.  

I have attached a screenshot.

I'm using Windows 11 Professional, VPinMAME build 822, and VPX GL 10.8 RC1.  I've also tried with 32-bit VPX and with non-GL.
![VPin-Studio_Funhouse](https://github.com/syd711/vpin-studio/assets/7355460/9f27c89f-0c91-46cb-99cd-c86c20c01608)

**Comment by buffdriver** [comment] 2024-03-04 22:09
Here you go!

[vpin-studio-server.log](https://github.com/syd711/vpin-studio/files/14487772/vpin-studio-server.log)
[vpin-studio-ui.log](https://github.com/syd711/vpin-studio/files/14487773/vpin-studio-ui.log)

**Comment by syd711** [comment] 2024-03-05 06:36
Thanks for providing the log files. I ran into the same issue, but couldn't figure out the root cause yet.
However, this workaround should repair the highscore again.
Use the "Delete" action and only delete the highscores. This will only reset the recorded values in the Studio database, not the actual scores. After that, the re-scan of the score should work.

![image](https://github.com/syd711/vpin-studio/assets/1169826/ffaffae5-5d90-4263-9800-89157ecfd16c)

**Comment by buffdriver** [comment] 2024-03-06 00:42
Thank you for the workaround--all's well now.  I will leave the issue open for you to close, either now or when you discover the root cause.

Cheers!

**Comment by syd711** [comment] 2024-03-06 07:53
Perfect, thank you for your response!

**Comment by syd711** [comment] 2024-04-12 13:21
I improved the error handling but couldn't find the root cause. I close this issue for know and hope I fixed this "by accident" together with some other highscore related timing issuess.

**Closed by syd711** 2024-04-12 13:21 UTC
Labels: bug
