### ISSUE TITLE
3.5.0: there are two of me!  duplicate entries in global player ranking (vpin mania)

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#450] opened 2024-09-07 06:09 UTC
**Describe the bug**
duplicate entries in global player ranking (vpin mania)

**To Reproduce**

Went to VPin Mania and all the names are duplicated:

<img width="2176" alt="image" src="https://github.com/user-attachments/assets/e2522383-5510-4f8a-b18a-a02902378f22">

[vpin-studio-logs.zip](https://github.com/user-attachments/files/16915050/vpin-studio-logs.zip)

**Expected behavior**

Less duplication

**Desktop (please complete the following information):**
 - OS: macOS 15

**Comment by syd711** [comment] 2024-09-07 07:00
I saw that too and it was gone after a reload. On it.

**Comment by syd711** [comment] 2024-09-07 10:21
Fixed with 3.5.1

**Comment by gorgatron1** [comment] 2024-09-10 04:37
@syd711 I ran into this again in 3.5.1.  As you mentioned a reload did fix it.

**Comment by syd711** [comment] 2024-09-10 17:16
I think it was because I build the last release with the non-update client for the vpin mania services.
Should be fixed with 3.5.2.
Please re-open this ticket if I'm wrong.

**Comment by syd711** [comment] 2024-09-14 11:30
Note to myself: I think the issue is caused every time a new score is submitted.

**Comment by syd711** [comment] 2024-10-02 11:01
Fixed with a timed re-creation of the list.
Fixed with 3.7.0

**Closed by syd711** 2024-10-02 11:01 UTC
Labels: bug, fixed, vpin-mania
