### ISSUE TITLE
[Enhancement] Show hint for tables with invalid ROM names

### ISSUE THREAD

**Issue by dmccombs** [syd711/vpin-studio#455] opened 2024-09-10 00:41 UTC
**Describe the bug**
For tables that support multiple ROMs like VPW's Twlight Zone, the table's ROM is shown as `tz_94ch or tz_94h` in VPin-Studio, and while the table works fine, trying to edit the Backglass settings results in an error saying `Table not supported (tz_94ch or tz_94h)`.

**To Reproduce**
1. Select a table like Twlight Zone with an "either or" ROM listed
2. Select Backglass in the side pane
3. Toggle the `Start as EXE` checkbox
4. Observe error

**Expected behavior**
Backglass settings should be saved correctly for the table.

**Screenshots**
![shot-2024-09-09_20-34-24](https://github.com/user-attachments/assets/6712d888-fe0b-4d20-bd1a-55955ba9811f)

**Desktop:**
 - Client OS: Archlinux
 - VPin-Studio version 3.5.1

**Comment by syd711** [comment] 2024-09-10 16:14
This is not a bug. 
The problem is that the ROM name for the table is not properly specified. A string like "tz_94ch or tz_94h" is not valid and therefore the error message is correct.

e.g. fo the Twilight table, the ROM name should be set in the Table Data Manager dialog:
![image](https://github.com/user-attachments/assets/126aa5a3-a259-4d8a-9f48-cf2896656f6b)

Otherwise a lot of options won't work.

**Comment by dmccombs** [comment] 2024-09-11 22:44
Ah, I see - yeah, the Twilight Zone table checks for a few different ROMs and uses what it finds first and is confusing things. Re-validating the table doesn't throw any warnings though, maybe it should throw a warning if this ROM name isn't set to a valid ROM name?

**Comment by syd711** [comment] 2024-09-12 07:26
Sounds good. I leave this ticket open because a whitespace is afaik always invalid and could be highlighted as error.
I'll change the title though.

**Comment by syd711** [comment] 2024-09-14 11:21
I checked the other tables and some of them are using whitespaces for the cGameName.
So this type of validator wouldn't work for them and I can't think of a reliable pattern that is applicable for all tables there.
I close this ticket for now as I see this rather as an edge case.

**Closed by syd711** 2024-09-14 11:21 UTC
Labels: enhancement

**Comment by dmccombs** [comment] 2024-09-16 01:17
That's reasonable. Thanks for looking at it @syd711!
