### ISSUE TITLE
[Feature Request] Media 'Cleanup' function

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#223] opened 2024-04-24 13:48 UTC
As I've been updating my FullDMD videos, I've noticed a lot of media that no longer has an associated table. A function that scans all Popper media folders and deletes media that is not associated to a table would be a nice addition to keep the file count down.

**Comment by syd711** [comment] 2024-04-24 13:54
Isn't this a duplicate of https://github.com/syd711/vpin-studio/issues/134 ?

This feature is under development from the Visual Pinball Back Manager guy. I'll integrate it once he is finished.

**Comment by Ltek** [comment] 2024-04-24 17:31
coool

**Comment by syd711** [comment] 2024-04-25 05:45
I close this as duplicate and will contact Matt (@Malibu) about the status.

**Closed by syd711** 2024-04-25 05:45 UTC
