### ISSUE TITLE
High Score Cards

### ISSUE THREAD

**Issue by yoshi98bc** [syd711/vpin-studio#95] opened 2024-01-20 14:59 UTC
I am not sure if this is a bug but when a new high score is achieved it doesnt update the other 2 screen in pinup popper when I exit the table.  I have to close pinup popper and restart pinup popper for the new high score to be displayed.  Should it work like this?  Or is something wrong?  Thanks

Great program by the way.

**Comment by syd711** [comment] 2024-01-20 15:21
Thanks you.

The highscore is generated...
- ~6 seconds after exiting the table
- when the table is restarted
- when you press the "scan" button in the highscore section

The problem is that there is no "Game End" event in VPin MAME or VPX. That's why I simply check the exit event of PinUP Popper instead.

**Comment by yoshi98bc** [comment] 2024-01-20 15:35
So if i wait 6 seconds and renter the table the new high score should be
there?

**Comment by syd711** [comment] 2024-01-20 15:54
Yes, if you have enabled the score cards on startup, you should also see the updated card then.

**Comment by yoshi98bc** [comment] 2024-01-20 16:09
I don't think i ever enabled high score cards. It just worked when i
installed vpin studio. Am i missing something?

**Comment by syd711** [comment] 2024-01-20 16:26
Yes, the should work ootb. But additonally, you can show them via the Popper screen via key-binding OR(!) by the VPin Studio server when a table is launched. There is a preference for that:

![image](https://github.com/syd711/vpin-studio/assets/1169826/5dd97049-6298-45f4-bbf2-9b89b953312c)

**Comment by yoshi98bc** [comment] 2024-01-20 16:37
Yes. Have that. Its great

**Comment by syd711** [comment] 2024-01-21 14:02
I hope I could answer your questions.
I close this ticket for now. Feel free to re-open it, in case I've missed something.

**Closed by syd711** 2024-01-21 14:02 UTC
